language: python

python:
    - "2.7"
    - "3.3"

install:
    - pip install coveralls --use-mirrors

script: py.test test_schedule.py --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
    - coveralls
